name: Func Check Source

on: [pull_request]

jobs:
  check:
    name: Check Source
    strategy:
      matrix:
        go: [1.16.x]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check
        run: make check

