# Build and test all pull requests
name: Pull Requests

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        # os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Clear Cache
        run: go clean -modcache -testcache -cache
      - name: Unit Test
        run: go test ./...
      - name: Build
        run: go build -v ./cmd/func

