name: Func Schema Check

on: [pull_request]

jobs:
  check:
    name: Schema Check
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: knative/actions/setup-go@main
      - name: Check that 'func.yaml schema' is up-to-date
        run: make schema-check
