name: Func E2E Test

on: [pull_request]

jobs:
  test:
    name: E2E Test 
    strategy:
      matrix:
        go: [1.16.x]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Local Registry
        run: ./hack/registry.sh
      - name: E2E Test
        run: make && make test-e2e
